jupyterhub:
    hub:
        extraConfigMap:
            memory:
                4096M:
                    - ENC[AES256_GCM,data:mF7CYlu1uPUT,iv:2dJVknmxlgUxSWkvv/Q5mz6LuIrknOVWUZ4fx9v93AU=,tag:XQ2Jw+dOywAvophrQcx3Ew==,type:str]
                1536M:
                    - ENC[AES256_GCM,data:LP1y6w==,iv:eRzOwASLfV4Ohr5vxyORcr+Z5HJP2ZmtLtjQTtXlqKE=,tag:XEqv95MUMaNxV9BsMVQmXg==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:DIoJkA1NRHypylJ6xoompfc=,iv:vAd0CcaF8A3iTCYPoMMU41ejZkiKjRyHJJAKc3ibbIY=,tag:6UPuyXcQOvVzIO/8yBG1EQ==,type:str]
                client_secret: ENC[AES256_GCM,data:Z8HUPX2gwX6snWYXD6qLwANxqWkDmX5FDygsFvE7RofGeu4DPEcdmzsPriJxxo3BW8GFy+8mv2jYEdpe7dXdyg==,iv:nTeWIs0AaYo9ihtufW5ydwDHkcD/P740bezd22d2n1s=,tag:iAMZbnDVxBBm1ubQYTNk9g==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:wwHWlTcl/zUHjEXuXuXjFEk5aXeYZum0j6g4xYa/Tq89p9GseJb54oDhw6AV3UyOT5ovdwJ+bA==,iv:v9vDjVXNzW5NfBJ1gPbWycjL5h/1Wd6/Wwi5YOh0noQ=,tag:FtuNEr/KyIxXgYovaBh6Qg==,type:str]
        extraContainers:
            - name: ENC[AES256_GCM,data:NePYXVO8tIHBlhaOcJWbyNlkAQ==,iv:1XpDvSKavyFHuUEh+PND/aZ3QaMYDeECVBPnrSbBivY=,tag:TQRSilm5EL2vWNSI35HiXg==,type:str]
              image: ENC[AES256_GCM,data:/tZoKZ/G/RHzruSiWy96SHoeotp6/8ZCQ7oEwmYCXEQZlm0=,iv:LZGyTAB7qoZFN1krApgScKoc2bWuJqyR4p5xdrvm/L0=,tag:wWix4IFoGYPEn4/aD9V2lw==,type:str]
              volumeMounts:
                - ENC[AES256_GCM,data:y0laoBMvXxq1XwidtsDppA5Ed+hYJmcI1vJxmuqYlsX5HLuhbt17zMAMDb7rMAx0tH0=,iv:X9Zv472tCOPkkVMArqx2NaaKe/wN7nXWnRLSmgwjYbM=,tag:kjNqiU/VZaekhW/9PaujdA==,type:comment]
                #ENC[AES256_GCM,data:y0laoBMvXxq1XwidtsDppA5Ed+hYJmcI1vJxmuqYlsX5HLuhbt17zMAMDb7rMAx0tH0=,iv:X9Zv472tCOPkkVMArqx2NaaKe/wN7nXWnRLSmgwjYbM=,tag:kjNqiU/VZaekhW/9PaujdA==,type:comment]
                - name: ENC[AES256_GCM,data:JS+1,iv:PVMUlW+kXbz/M237WA56CcbfDC5EjUJbSTpSHjjgpKw=,tag:2Q6KF0ERz++4d8wNcycWwA==,type:str]
                  mountPath: ENC[AES256_GCM,data:f2lzGtU38YybaFo5bDdZ,iv:YON4ECNjoUNnohG2RmPQWUmsgYh77gyDfC8lqoFsM4I=,tag:43WwPW/tyvTxY3vRbxpeGg==,type:str]
                - ENC[AES256_GCM,data:haP7Fs1WRJmop5G0xdx/l2X4LVndd7Qn,iv:+UjEvPgVJ9ED2JaPqAZCdgJnSDJ5VIK2mOR1LQE/uF8=,tag:vQ51GB2Kjrdw2fk7nXI+eg==,type:comment]
                #ENC[AES256_GCM,data:haP7Fs1WRJmop5G0xdx/l2X4LVndd7Qn,iv:+UjEvPgVJ9ED2JaPqAZCdgJnSDJ5VIK2mOR1LQE/uF8=,tag:vQ51GB2Kjrdw2fk7nXI+eg==,type:comment]
                - name: ENC[AES256_GCM,data:wYmDFEPl,iv:5bt0XEe9h61Pz/5Aff3uRk409jwKMXYURCuFnFX1phA=,tag:BwU6mb0Cqc8/qxMBF5uI4Q==,type:str]
                  mountPath: ENC[AES256_GCM,data:iVEtlfrywnpHhaO7AinN0tWFxAL5fQ==,iv:Yuexxg6CS7AUHMUKoPqFSYJjphXTSVyQVmbrZRVRfVM=,tag:E0yU8wDAZieMli/5KwQ2IA==,type:str]
              env:
                - ENC[AES256_GCM,data:n2v0N6bumaeNBNKmeSn8RYY=,iv:LODDWFKKJtpoSa7KX/F/OUkzamXsY6SZJKV/RSPG6Ls=,tag:ypXFIdOOmrezHin+LBNkMg==,type:comment]
                #ENC[AES256_GCM,data:yrsFZIce/dVfVqzpwDWpbcs=,iv:LE+BF9PvQrFpM27F/tF8mV3qgX5Po+qC92TUDpSxnG8=,tag:e6Vl84O1W/bOAcu1mzBD6A==,type:comment]
                - name: ENC[AES256_GCM,data:CzABDK1hprhS,iv:acJOK3S1Rr5l7JnKY77nmTLn2L+NZbzgFtUxDEcAb8w=,tag:ZSAI0tifuPI8Tf3v89DRGA==,type:str]
                  value: ENC[AES256_GCM,data:9frRKZdu1Po=,iv:bM9tcPTCmaWAUfZ2OSUmK6g2wNCsb40E9MkkGM90gdM=,tag:coyjoX1bS+vLFsymhuKuXA==,type:str]
                - name: ENC[AES256_GCM,data:v3cBp1F6s3vDXg==,iv:OXZPFgpYgwonBu9Ec3NkFUrc9qFGYZxbc8CWJVbs+jU=,tag:k1INmM6s7MdeQbqcZXD/2w==,type:str]
                  value: ENC[AES256_GCM,data:QMlCHBi9ANH+LrW7UZQAujZQp58oADsECQC7M41LO1A=,iv:3Lnw/xjxfyW00MqC55KURe8BTENDOhcuuYy5pjUJ18M=,tag:+jU2JNjkmnEbwe2vrJ2klA==,type:str]
                - ENC[AES256_GCM,data:RgGuqz9L2asGNA==,iv:1fh7GlqZRrvfFu+GvtUCS5gCIXBAKEAIcmZJ9lhYucQ=,tag:MEPjsRurnvOKAukj9SUuOw==,type:comment]
                #ENC[AES256_GCM,data:0t1usokNfAQ+5A==,iv:D+xUA3go5PbRZFAmLNb6gMQH3L8OeAKhvTH9NTiem4o=,tag:O+nmZfB+DLEGlVaRtdPj/A==,type:comment]
                - name: ENC[AES256_GCM,data:d6WtzVWFnWs98dIIfYI=,iv:Vp3EAWOy3Ue7bDEAMwsHPomU4M5fS64likfnUhnmyhk=,tag:nmHquT97sGYr7u01Bd8+mA==,type:str]
                  value: ENC[AES256_GCM,data:YVHUGhmcsAo=,iv:I+i4WMX/SlJxLxUAwU1z59Ed6OfKfu9PGSmIi2WjZVs=,tag:JkW41vmtfrxZ9x1gdeA4Dw==,type:str]
                - name: ENC[AES256_GCM,data:838jPZmf4WZabMizk4YN,iv:ag8CaA0KgLy6EIuPHuIq6vrUGZ7RWr8uXAKy3A1p2sA=,tag:YYbZXkNsneLFGLKNFkmD3w==,type:str]
                  value: ENC[AES256_GCM,data:Xwr1rCgWz3wM/DMt4dMpXoVN2YszxkOZUcJT4IvS8aw=,iv:aKfHr2EiE/gRMt4uqBv84zmoJXvFI5T+S01D5sHtYnY=,tag:KD2h+agt78CzCf7QAeEEyw==,type:str]
                - ENC[AES256_GCM,data:w5Q9k4vHGG/qyqxEvzuY,iv:awLmL1qaBCi7ZbpiFvxvP2qTg48S6QQdCgjpZcM9Ivk=,tag:G9l3nVy/HEEPQMqzhJQrng==,type:comment]
                #ENC[AES256_GCM,data:KiiJJBSOiJ5Amg3zxw4X,iv:hV5YwALx8Ud+4BgtbwEkrxC6GFTWJ/QOZ4rLZB5Wmr0=,tag:vYZ5gCKVw7yIJTJ+Y+9DEA==,type:comment]
                - name: ENC[AES256_GCM,data:gKZs5Ba6cQzKad7bKseVam5b,iv:dydwJ9WMfvzWjviVcPba4OwATCK4QFI5R36kvS0H8OM=,tag:weqM0VjfPJcHcQ+Bdp8ZdA==,type:str]
                  value: ENC[AES256_GCM,data:xs9NCumGhLE=,iv:wKw8FWPwJP90clrlnWwOMwXlqilMCLXK3WaP5eXXaOs=,tag:xP5jYb1kij2gybiDU+Of/A==,type:str]
                - name: ENC[AES256_GCM,data:4IYAoFuAtkAvq56i9kVxsXdDtg==,iv:BU4VmAf0JmLV1UXgUhdcjDuSzv0yHYh/5b8q/cS9bU4=,tag:hNneqOthtGEJ0H4ZKBkpsg==,type:str]
                  value: ENC[AES256_GCM,data:YP1dREfl4gpanjeateeA9O3+PYs0zhBEni/PVDXQOdE=,iv:NMt7WIQbjf5I+Vk551kXLR8QvLR2VS1SrfSd8KqS8ho=,tag:OhBtwMLWFMv3Yqg3RMT6SA==,type:str]
                - ENC[AES256_GCM,data:ybo4i2DoUXgmoDyb,iv:x/wSU7mxqOnZ6QPqmaVDpw4duoEmM8etx1EeR8g/QiM=,tag:d3i0bz97ZdgtBG5nLNzVKg==,type:comment]
                #ENC[AES256_GCM,data:NYiKj8/XoaxUr50E,iv:uwPfpgZAUEQqtlrcG4gg0xT5S/n84kvqUoz5/wKs2NY=,tag:PQaay4jggI8005R03I3xAQ==,type:comment]
                - name: ENC[AES256_GCM,data:QV2GnLdh2JSXEJrGg4io,iv:2N58HGvKDBVMoTTaWBHjLeDtWzbkEVFrvicN/TAdazY=,tag:R/JInYkzKqHw5yN46ap3Zw==,type:str]
                  value: ENC[AES256_GCM,data:7uSFWr9hxaU=,iv:uXheSRCQZA48G3GAqe5wSX6JWhL3pdlyvkCy9fXdzi4=,tag:FeRCh2utr8wIyo0G1RpNmA==,type:str]
                - name: ENC[AES256_GCM,data:xE+nEPnEHptGVzo3AoAdYQ==,iv:Add+3BWM2590CVdT5GVJ58587gTwK3o+Ztbm2v3wc0E=,tag:iX9H9FfnVt8LUz+GK2t2qQ==,type:str]
                  value: ENC[AES256_GCM,data:AdOea0X/GDC5AE1DL5cC6kylBtxe/kD/Q8o6CFgKi/M=,iv:VZc1TkvP5lv/40Lf0ui8UHQyYRPOsz5FqExJnocRgnQ=,tag:ejpMN25ub8HgUkehuonc2Q==,type:str]
                - ENC[AES256_GCM,data:9bmMRkFIg+bfsA==,iv:59Wo99gwdQtIyPPXQz1iYponcO+uTy6T2Xqj5JMXhFE=,tag:xBZDoFYC4B2fJ9uurRJAhw==,type:comment]
                #ENC[AES256_GCM,data:Jh3/BoYkIDkUcA==,iv:oohPSTRzYq/p0vVpu3ktpBDDXvXvVD8Gj4b7EGNBE3k=,tag:KaN6FIutpxGcJ2ek6GOQzw==,type:comment]
                - name: ENC[AES256_GCM,data:5Q6RHOx6u6U/aQcL,iv:A+9FtpGI9isFSzGBHKXxMMD4Ll7O2EmOaLukHjYNO4o=,tag:FWFS3fdh+F/6O9IRvBa6Vw==,type:str]
                  value: ENC[AES256_GCM,data:EyvqRZVURSY=,iv:O7r0cXpDbWEPcKsMQDS0oXqouIjX6jTS7BJiD9/hE2U=,tag:NFuiht9VuyzRH5ROfuZNJg==,type:str]
                - name: ENC[AES256_GCM,data:3Leqy22MyI8H4CDoCA==,iv:8ZxuOuIqTy0V6NRkapNyQosj+zxKRlSsDFCmy5zYWU4=,tag:EesrGrTDFlH6pSQBZBdOlg==,type:str]
                  value: ENC[AES256_GCM,data:T6u71J9NjC3/ogILqImi1oqHXgIhhaoLImUR3R4uELc=,iv:XhqEeXHc2kZi34dg5YtHaVCWeLkcP1xARC/9FZH4fCA=,tag:xxXMjFaagbbFNcFHRBEm5Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:58:00Z"
          enc: CiQA67O9ALpoZQdDjz4LYoS02B/Pf+TZfImPg6v2Q0Xnbd7r1cQSSQDmhpq8qcl0J95ZZpcyBAwzpB6AMCEtjhkrX8dOvb+nGfyWYSBMi9xeakYuwrbRiblRrhDyvnj1sdSs0OmwiQ8YQ0eD7/G1StM=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T17:20:44Z"
    mac: ENC[AES256_GCM,data:SMj8uyIv5B2OW6dkGncb132PuToHz2tRKvVQ8YTpzr14rBlOv4lLX86XY+ygwiV+7fnC7FQQ7PbC03W2e8LPD0TLwcv3oBy2oFEC2EeNR3K8XfiRbIV0CsW85d5dsFj+KlraXX5DaowEtmgrZpS6FHtxJrS9kyxseybw+cT5fYE=,iv:7mR64PTSJDxH6K1a+xUEf+9n3bmCigs7XFST4SK13UU=,tag:hzw94eMFF1ZOV5Eo55689A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
