jupyterhub:
    hub:
        extraConfigMap:
            memory:
                4096M:
                    - ENC[AES256_GCM,data:jx9c70P2fP9R,iv:d3mT6n5aR5GjdVXPVWTJUdLXuiyqmEPVai7byHjAJPY=,tag:g6xD7WN9b59WEtWri5YfpA==,type:str]
                1536M:
                    - ENC[AES256_GCM,data:1z+tqg==,iv:ZbE6GP2iEjTfcgEz4rYlzTpNTCG7o2w+oWwspYzdziQ=,tag:iyhDrBx6YNfUtOIRrYai7A==,type:str]
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:6tlrB+xqli/9ejquhG8Jmsk=,iv:7Gjy2FLrnQBoKc4zaSN+fw4uXpAY5rzhQmhru4EP7YE=,tag:wQr2onNw7bDXkdMjZeSekw==,type:str]
                client_secret: ENC[AES256_GCM,data:QQowye87vY550m9egNYvqJKuEMl4LL9UpdNfeq3ha6OQ1/qsTHRA685y51uFxZKmsIFXo1s2wzdgkX9l3WUWIw==,iv:Xl2YE76miBJmYTBovv6R36c+c+U8GJlRS1qU8zYSXgw=,tag:lXuFn3mHdZU8XmozjchlQQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:jrwgy+xmyUrBkYy+1cA7Wsmtio1xJ7xBXRffW0vLHlZb31wZmJoYlTp6njij7Ih13eQDItLggorqSV167cZo,iv:qz0tvBs7Wpx6bVZcgfGX5gW7aOYZ0QhZYmhoDqYv1bk=,tag:pGKs2wOvKvmZNguii1GzHw==,type:str]
        extraContainers:
            - name: ENC[AES256_GCM,data:VkPzr9A9cv6wyzgxw82Ys92GqQ==,iv:K89VB2uxwIIdS6BQyp7J+Hy/84teZIKdukVljR1cu5s=,tag:hKznMpPy/6WsLm1myDLLAw==,type:str]
              image: ENC[AES256_GCM,data:YFPHi2/q0mA2JVoZssudz7huWRjXVm37zJPpNhTjKdMYYgM=,iv:/9b98xA8KnB9j0TuJrIKD9ZVCUoKTjn3rhxRMR60K3k=,tag:GOywqDX6bcTn707veatM1g==,type:str]
              volumeMounts:
                - ENC[AES256_GCM,data:NztkyUMD/0hviMceYewFFGf0Y2d5CbE3AD4w40gO02ckGnyzjvNBLbQhL9Vt64f5FpQ=,iv:HEp1AONHGuy36WLM520QVJH01NIt7xpzWgdW/gLVqsY=,tag:7faBJHvCZ55v7uds+eGb5Q==,type:comment]
                #ENC[AES256_GCM,data:NztkyUMD/0hviMceYewFFGf0Y2d5CbE3AD4w40gO02ckGnyzjvNBLbQhL9Vt64f5FpQ=,iv:HEp1AONHGuy36WLM520QVJH01NIt7xpzWgdW/gLVqsY=,tag:7faBJHvCZ55v7uds+eGb5Q==,type:comment]
                - name: ENC[AES256_GCM,data:ceQO,iv:LdFGNmDzAoPQ08t9lQbKYEinXL7HQLWQRQl+UG8V3xQ=,tag:qNrM9lEIiaFbQRSi7tBRig==,type:str]
                  mountPath: ENC[AES256_GCM,data:STtbp82euRo3PEMdtdiB,iv:mpZC+nsuZfP9CAYZlrQER99CKBVOXqqaulrihl9hCSA=,tag:j7+VE/lWXPNDGGmrXNrQKA==,type:str]
                - ENC[AES256_GCM,data:+rYMJFHmDcjeYDqIV9UWpCV9dNGQMVNu,iv:AC9F9ZOK+I3kj5ZGIhl92DW3ZefAG5FK71VfMQCcgxg=,tag:Qs+if4DQGk/aM09MLGnhcQ==,type:comment]
                #ENC[AES256_GCM,data:+rYMJFHmDcjeYDqIV9UWpCV9dNGQMVNu,iv:AC9F9ZOK+I3kj5ZGIhl92DW3ZefAG5FK71VfMQCcgxg=,tag:Qs+if4DQGk/aM09MLGnhcQ==,type:comment]
                - name: ENC[AES256_GCM,data:RgNDfMCd,iv:4zYFIQ+Z3PGwadkwtwoNqQTEr0WNg7kvUhanmHKeAeE=,tag:Ao/oxVbm6FjX5KqNEPRgpg==,type:str]
                  mountPath: ENC[AES256_GCM,data:CebwlNqAHAgWfqQjp4M3MhcMr4dffQ==,iv:AaIxVMxFm3TOs8U5S19LYUNGERsjO4px40xXNLrFvjo=,tag:3JFaa/3UHAKefAaF7xT+EA==,type:str]
              env:
                - ENC[AES256_GCM,data:jj3UoAoQc4TgkbyU4Fes/WI=,iv:kCfFZeqhPDZU8tse2LOinZ78biW4OHQIku5WhBJJfvM=,tag:szjS4WmxxcUIlNsIUCn+yA==,type:comment]
                #ENC[AES256_GCM,data:+osSyefqm5NOZvkfxQXlpY4=,iv:4v6Mh//tokQ24pROuxOLXbLkikfN1whKa38+fD/XkPw=,tag:+58faB2oxwPQ6F5YlZa5ww==,type:comment]
                - name: ENC[AES256_GCM,data:z3ShI/CDTaBj,iv:MQNc5nMV8x+EYjUKkpIY8CLHKwht0UlLsif8HgcQEg8=,tag:QRKnkjhtTRMB1QJklYey5g==,type:str]
                  value: ENC[AES256_GCM,data:g/U2uXw1FG0=,iv:epqlYfx2ZpjYQ03appJSNNmAgerOxXvwb0P3BbjmU/E=,tag:IiY+rEjmoJzFTiCgdrNQNg==,type:str]
                - name: ENC[AES256_GCM,data:K8oy+ZG3sV4XCg==,iv:2YB7p+4JrG4hWfSIG0/i/vlqobUECBhKyJSZ3XqTmu8=,tag:UT+xltXX+sPKHeqVCavIKQ==,type:str]
                  value: ENC[AES256_GCM,data:iN1O/dUflG+SeSKpqBgfAxj584OkCoim/2VXVSbIyn0=,iv:YGLn+29Aag2zVfLMbbOGtIGqXtHEdatD513uGXJx4Wk=,tag:3o1uL6AOVQ8ReOvKoa0Dbg==,type:str]
                - ENC[AES256_GCM,data:m9XBUDbGlykPzQ==,iv:VxT75DY07OXSD1+AX+w3a+WDzmYtIM0UY8Lcc0OdNMw=,tag:QQ7DBqEpX1Hl7LHculHkKA==,type:comment]
                #ENC[AES256_GCM,data:so7jH6ZlJKIefg==,iv:e2YG6lVg0XA+dTZqR7UAHyWRZxtVOFxgRNFMjD8aZGg=,tag:+gIN5EAYwuexQ/mSkv1yxw==,type:comment]
                - name: ENC[AES256_GCM,data:YxSHWRx6ZBmgvkxxDqI=,iv:49HV4bwnjD4S8zvmt+pfX8RGWRMxrZ+f4uACosx7+aY=,tag:yTOd6yUEq7J6hpq4kX4gyQ==,type:str]
                  value: ENC[AES256_GCM,data:ZXYQFP2kHU4=,iv:Mfw7SWRqTqCj73dx6KzXLUOVkBFnv80fgFGvBsjKJ0o=,tag:fIrLbo5fsPPXCbW5i2qtCQ==,type:str]
                - name: ENC[AES256_GCM,data:wAUibkWhwU5pLgOQtlKc,iv:irRQBTuky4Dd5qGDNkNyhBmt3UGafqsqC7jjQsojeuo=,tag:jUNvPpTXJ73HWORkQSYk1w==,type:str]
                  value: ENC[AES256_GCM,data:TMOKGsEBkkYR/amXhyGGpqsnoNJEqElt4t3eT7TGASs=,iv:HcdqXzWCBmx1ppTHR38y5WLnDAb4gRrkP8w8iH1xcXo=,tag:Qxk9MEyyvhcblxy9at+Cng==,type:str]
                - ENC[AES256_GCM,data:kWTSwdqZjlIBq3A8PbSZ,iv:P84E7usBjdEhFLTT5IzOWjjGmv3VyUi5i7PLqDvQ/GU=,tag:mqsQTVRqEiKOo7IdWNz+rQ==,type:comment]
                #ENC[AES256_GCM,data:ImF2yB0NjcrmVvlb77sK,iv:TybCRrYceJZ8Ga/gHJ5Kebq78XinN9pNamzKT+JVuF0=,tag:5gq6IeechggGnLaZmI44iA==,type:comment]
                - name: ENC[AES256_GCM,data:s2sC9uYrFEdw3o5/giyfnZWQ,iv:xvLwc2lrluqV/fRcIkg5hSnC75jHnnzPsrnnYft3glw=,tag:Wgjv488qzKoPitRDH7aZyw==,type:str]
                  value: ENC[AES256_GCM,data:EyCjiZA3Q/o=,iv:1Ot1Jb2v+bF3DuJ51paORUVQqaJwqMWbZKYCxAz9k8k=,tag:2rR2KlvDgnKv42gObAttMQ==,type:str]
                - name: ENC[AES256_GCM,data:dwl6uMIltPAtJs4yU4SQ/rlaEQ==,iv:H/GZkjiBPxybAEqfxWbm3JsJEaLYiW58VoBBpFVuI7Q=,tag:YqUOJZMSws2+TdrZOkPrww==,type:str]
                  value: ENC[AES256_GCM,data:7sd86VwPlqQ0x2tNI3Yt0eDDNvkDsEUE3JwMF4ryB9I=,iv:79suHdzfmnLLhPwkMfhZXGIGwm1pkuufa7ghOKZZdPA=,tag:rqbj4HUsftVpjsvMP0bZrg==,type:str]
                - ENC[AES256_GCM,data:ce+TarYRQ++VL/fP,iv:ujQLa6MrG//nnfofwpcpHtuJMCGVYHg0pFhYD7fzqrU=,tag:wA4iaii0HkJV+VRXxlh/Uw==,type:comment]
                #ENC[AES256_GCM,data:qPb74GnYhepSxDgK,iv:JH6tA7hu60j62IxCN0UEcWjSiEJz2yx58ljEQsVLdnw=,tag:lYILTUuWO8b2crBlwr9+EA==,type:comment]
                - name: ENC[AES256_GCM,data:EST5ZZo2vxFsq7qlAZtF,iv:IGvU4CGS+/UdY5KfbxbQYlWQT2nNonBzjNXEs5Q93zE=,tag:KfZpA/AvgtLu3HRKyLWY3Q==,type:str]
                  value: ENC[AES256_GCM,data:UOuEUItmB8c=,iv:I3Ze8WBhfpnWQlOOh49Dv9tBzb/VhVkMRynZq8niAXM=,tag:tiA9lbtgoK3ID+tTi2/LGg==,type:str]
                - name: ENC[AES256_GCM,data:Cm1z4TsLGJJcrHjU9z1UsA==,iv:J/5KHh43ephkaLz7yeRtltP2YwX911T2QDkWGXa55h4=,tag:aX5ZqAlnN7lNTWE+s8JJ5A==,type:str]
                  value: ENC[AES256_GCM,data:iuzMmky0soY6Fl6dgd7OebP5Bx0PEmBr5FODQHy7lbw=,iv:RhT8HYcwhPpSh0r+TqJKSPjm2gw+O1fqZ/z7D59Z6fg=,tag:E/6lfLQbWfZ58Sst7EKIJA==,type:str]
                - ENC[AES256_GCM,data:J8/8Zu4CCwN9vA==,iv:RHGDGdkIdRqpYGYpueYXmuS8c7V6qwohB7s0r6OGzAU=,tag:0sOFtYyab19+utOds6/fCg==,type:comment]
                #ENC[AES256_GCM,data:AnnunyM+2aAEHg==,iv:/rRjp96eYYRrAmsvqvYmGHN9LOGq0YPVCh6MgMyftIg=,tag:pEDlxq1JKYUscULuVUk+iA==,type:comment]
                - name: ENC[AES256_GCM,data:1sFKG/ihhbSdbg8J,iv:SBLsVLrY4g/+j1rOubrj7fh0+zvVAVF4eW8EHZj4FDo=,tag:FYmmfYHRJreKB2GXN3mJwg==,type:str]
                  value: ENC[AES256_GCM,data:9puegBDrGsE=,iv:luSqIX15AiOFIP3OcmfrcjzQPs4wmYa53ddAhNVwOlY=,tag:G1MM+irDHVQRqNH0F+LBRA==,type:str]
                - name: ENC[AES256_GCM,data:u9+gr0jsd5yIo6MpDg==,iv:MItuvZbws5zYS5rbNQxqplXPkttkf0qdf7yiZrxtj9E=,tag:X2fSrT01hHNIVfpuiW6aRA==,type:str]
                  value: ENC[AES256_GCM,data:M3aegzqrgmTznJIY2TRQsJ609xkBrL+BW1oerK920PM=,iv:wn8q+HB98IKtd3P/eexB+3gFnJmt0caegXFjmqtsO6Q=,tag:BOju5Rm4mg33CXlXJkJh2A==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:59Z"
          enc: CiQA67O9AIxTFmAaS7Bn4Z7Ajn2VoJZAViDi/WlDGi70sDj5R0wSSQDmhpq8XeOOpmygjHorUvvXdUfujdzf6cSD1IPuz3JUc900UGL5QtXFfLMsfOb2fJrV/h9xhm8Kd1Ub3WF/rSpdG2HuS7kn6PA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-05T17:20:30Z"
    mac: ENC[AES256_GCM,data:/hdruwFvXSj/4DyD4v8exT43vvIZRjZzbTMH33nn5Bf3i8dzr83NndEvv3lvkU6z0QGku4dFhcFaihxace/0ATtF5Gc7gemEONX4nsH+ksCj2Brpap55s6f0E3Ky3q8jRzhF4AhZ8SmtaFuVVpFTSWAgw6F/5O6jRlyZSMUQhpU=,iv:2u0F4RMzwFvOJTLoBg9ctPeLdojr8dQlQaRZqI5+hQg=,tag:Cc2/MQqD0ib4naQ8J+jNkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
